tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        'surface': '#131313',
        'surface-dim': '#131313',
        'surface-container': '#201f1f',
        'surface-container-low': '#1c1b1b',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'surface-bright': '#3a3939',
        'surface-variant': '#353534',
        'secondary': '#49f9f9',
        'secondary-container': '#00dddd',
        'secondary-fixed': '#49f9f9',
        'secondary-fixed-dim': '#00dddd',
        'on-secondary': '#003737',
        'on-secondary-container': '#005c5c',
        'on-secondary-fixed': '#002020',
        'on-secondary-fixed-variant': '#004f4f',
        'primary': '#ffb2be',
        'primary-container': '#e0115f',
        'on-primary': '#660026',
        'on-primary-container': '#fff8f8',
        'on-primary-fixed': '#3f0015',
        'on-primary-fixed-variant': '#900039',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#e4bdc2',
        'on-background': '#e5e2e1',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'error': '#ffb4ab',
        'error-container': '#93000a',
        'outline': '#ab888d',
        'outline-variant': '#5b3f44',
        'background': '#131313',
      },
      fontFamily: {
        'display-xl': ["Anton"],
        'display-xl-mobile': ["Anton"],
        'headline-lg': ["Anton"],
        'body-rt': ["Geist"],
        'subheading': ["Geist"],
        'mono-label': ["Space Mono"],
        'kanji-decorative': ["Epilogue"],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
      },
    },
  },
};
