/**
 * shared/cloud-status.js
 *
 * Shared cloud connection status indicator logic used by all 3 apps:
 *   - KAMAKAZII STUDIO 3D
 *   - VECTOR STRIKE: OMNI
 *   - AERO COMMAND // KAMIKAZZI 3D
 *
 * Each app can have its own CSS class naming convention via the `statePrefix` parameter:
 *
 * | App               | Base class              | State prefix   | Example full class                   |
 * |-------------------|-------------------------|----------------|--------------------------------------|
 * | Vector Strike     | `cloud-status-pill`     | `cloud-`       | `cloud-status-pill cloud-connected`  |
 * | Aero Command      | `cloud-status-pill`     | `cloud-`       | `cloud-status-pill cloud-connected`  |
 * | Studio 3D panel   | `cloud-status-dot`      | `cloud-status-`| `cloud-status-dot cloud-status-conn` |
 * | Studio 3D status  | `status-cloud-indicator`| `` (empty)     | `status-cloud-indicator connected`   |
 *
 * Usage:
 *   import { setCloudStatus, initCloudRecheck, CloudState } from '../../shared/cloud-status.js';
 *
 *   // Update an indicator using defaults (Vector Strike / Aero Command convention)
 *   setCloudStatus('my-indicator', CloudState.CONNECTED, 'Cloud connected');
 *
 *   // Update with custom prefix (Studio 3D panel dot)
 *   setCloudStatus(dotEl, CloudState.CONNECTED, 'Connected', 'cloud-status-dot', 'cloud-status-');
 *
 *   // Update with no prefix (Studio 3D status bar)
 *   setCloudStatus('statusCloudDot', CloudState.CONNECTED, 'Connected', 'status-cloud-indicator', '');
 *
 *   // Wire click-to-recheck
 *   initCloudRecheck('my-indicator', async () => { ... }, 'cloud-status-pill', 'cloud-');
 */

/**
 * Cloud connection states.
 * @enum {string}
 */
export const CloudState = Object.freeze({
  CONNECTED: 'connected',
  DISCONNECTED: 'disconnected',
  CHECKING: 'checking',
});

/**
 * Known state class suffixes (generated by appending state to a prefix).
 * Built dynamically so removeStateClasses can strip any of them regardless of prefix.
 */
const STATE_SUFFIXES = Object.freeze([
  'connected',
  'disconnected',
  'checking',
]);

/**
 * Remove any existing state class from the element (matches any prefix).
 * @param {HTMLElement} el
 */
function removeStateClasses(el) {
  const classes = el.className.split(/\s+/);
  const kept = classes.filter(c =>
    !STATE_SUFFIXES.some(s => c === s || (c.endsWith(s) && c.length > s.length))
  );
  el.className = kept.join(' ');
}

/**
 * Update a cloud status indicator DOM element to reflect the given state.
 *
 * @param {string|HTMLElement} element      - Element ID string or DOM element reference.
 * @param {string}             state        - One of CloudState (connected / disconnected / checking).
 * @param {string}            [title]       - Tooltip / aria-label text. Omit to leave unchanged.
 * @param {string}            [baseClass='cloud-status-pill'] - Base CSS class(es) kept on the element.
 * @param {string}            [statePrefix='cloud-'] - Prefix prepended to the state name to form the state class.
 */
export function setCloudStatus(element, state, title, baseClass = 'cloud-status-pill', statePrefix = 'cloud-') {
  const el = typeof element === 'string' ? document.getElementById(element) : element;
  if (!el) return;

  const stateClass = statePrefix + state;
  removeStateClasses(el);

  // Merge base class(es) with any other non-state classes already on the element
  const existing = el.className.split(/\s+/).filter(Boolean);
  const baseParts = baseClass.split(/\s+/);
  const kept = [...new Set([...existing, ...baseParts])].join(' ');
  el.className = kept + ' ' + stateClass;

  if (title !== undefined) {
    el.title = title;
    el.setAttribute('aria-label', title);
  }
}

/**
 * Check whether a DOM element exists (by id or reference).
 * @param {string|HTMLElement} element
 * @returns {HTMLElement|null}
 */
export function resolveElement(element) {
  if (typeof element === 'string') return document.getElementById(element);
  return element instanceof HTMLElement ? element : null;
}

/**
 * Wire a click-to-recheck handler on a cloud status indicator element.
 * Automatically:
 *   - Sets the element to 'checking' state on click.
 *   - Guards against concurrent re-check calls (in-flight guard).
 *   - Calls `onRecheck` which should call `setCloudStatus` with the final state.
 *
 * @param {string|HTMLElement} element       - Element ID string or DOM element reference.
 * @param {Function}           onRecheck     - Async callback invoked on click.
 * @param {string}            [baseClass]    - Base CSS class passed to setCloudStatus on click.
 * @param {string}            [statePrefix]  - State prefix passed to setCloudStatus on click.
 * @returns {Function} A cleanup function that removes the click listener.
 */
export function initCloudRecheck(element, onRecheck, baseClass, statePrefix) {
  const el = resolveElement(element);
  if (!el) return () => {};

  let inFlight = false;
  const handler = async () => {
    if (inFlight) return;
    inFlight = true;
    setCloudStatus(el, CloudState.CHECKING, undefined, baseClass, statePrefix);
    try {
      await onRecheck();
    } finally {
      inFlight = false;
    }
  };

  el.addEventListener('click', handler);
  return () => el.removeEventListener('click', handler);
}
